export const CONNECTION_TYPES = {
  INTERNET: "internet",
  WIFI: "wifi",
  BLUETOOTH: "bluetooth",
};

export const DEFAULT_CONNECTION_TYPE = CONNECTION_TYPES.INTERNET;

export const FIRESTORE_COLLECTIONS = {
  CHATS: "chats",
  CONNECT_CODES: "chatConnectCodes",
  CONNECTION_DIAGNOSTICS: "connectionDiagnostics",
};

export const CONNECTION_LABELS = {
  [CONNECTION_TYPES.INTERNET]: "Internet",
  [CONNECTION_TYPES.WIFI]: "Wi-Fi",
  [CONNECTION_TYPES.BLUETOOTH]: "Bluetooth",
};

export const CONNECTION_ACCENTS = {
  [CONNECTION_TYPES.INTERNET]: "#2d6cdf",
  [CONNECTION_TYPES.WIFI]: "#0f8f6f",
  [CONNECTION_TYPES.BLUETOOTH]: "#6a52d9",
};

export const CONNECTION_OPTIONS = [
  { id: CONNECTION_TYPES.INTERNET, label: CONNECTION_LABELS[CONNECTION_TYPES.INTERNET] },
  { id: CONNECTION_TYPES.WIFI, label: CONNECTION_LABELS[CONNECTION_TYPES.WIFI] },
  { id: CONNECTION_TYPES.BLUETOOTH, label: CONNECTION_LABELS[CONNECTION_TYPES.BLUETOOTH] },
];
