import { StyleSheet } from "react-native";

const chatListStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#eef3fb",
  },
  container: {
    flex: 1,
    paddingTop: 16,
    paddingHorizontal: 18,
  },
  scrollContent: {
    paddingBottom: 28,
  },
  heroCard: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#dce6f4",
    shadowColor: "#0f2c5c",
    shadowOpacity: 0.09,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
    marginBottom: 14,
  },
  title: {
    textAlign: "center",
    fontSize: 25,
    lineHeight: 30,
    letterSpacing: 0.2,
    fontWeight: "700",
    color: "#1f2430",
  },
  subtitle: {
    marginTop: 6,
    textAlign: "center",
    color: "#5f6f87",
    fontSize: 14,
    lineHeight: 20,
  },
  formCard: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dce6f4",
    borderRadius: 18,
    padding: 16,
    shadowColor: "#0f2c5c",
    shadowOpacity: 0.09,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  label: {
    fontSize: 12,
    letterSpacing: 0.2,
    color: "#4a5c77",
    marginBottom: 7,
    marginTop: 4,
    fontWeight: "600",
  },
  input: {
    borderWidth: 1,
    borderColor: "#cfdaeb",
    borderRadius: 13,
    paddingHorizontal: 13,
    paddingVertical: 11,
    fontSize: 15,
    color: "#1f2430",
    marginBottom: 12,
    backgroundColor: "#fbfdff",
  },
  button: {
    marginTop: 6,
    backgroundColor: "#2d6cdf",
    borderRadius: 14,
    alignItems: "center",
    paddingVertical: 14,
    shadowColor: "#0f2c5c",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  buttonDisabled: {
    backgroundColor: "#9db7ea",
  },
  buttonText: {
    color: "#ffffff",
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  modeRow: {
    flexDirection: "row",
    marginTop: 2,
    marginBottom: 12,
  },
  modeButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#cfdaeb",
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: "center",
    marginRight: 8,
    backgroundColor: "#fbfdff",
  },
  modeButtonSelected: {
    backgroundColor: "#2d6cdf",
    borderColor: "#2d6cdf",
  },
  modeButtonText: {
    color: "#556072",
    fontSize: 13,
    fontWeight: "500",
  },
  modeButtonTextSelected: {
    color: "#ffffff",
  },
  settingsCard: {
    marginTop: 14,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dce6f4",
    borderRadius: 18,
    padding: 16,
    shadowColor: "#0f2c5c",
    shadowOpacity: 0.09,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  settingsTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1f2430",
  },
  settingsSubtitle: {
    marginTop: 4,
    marginBottom: 12,
    color: "#5f6f87",
    fontSize: 13,
    lineHeight: 18,
  },
  recentSection: {
    marginTop: 16,
  },
  connectCard: {
    marginTop: 14,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dce6f4",
    borderRadius: 18,
    padding: 16,
    shadowColor: "#0f2c5c",
    shadowOpacity: 0.09,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  connectTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1f2430",
  },
  connectSubtitle: {
    marginTop: 4,
    marginBottom: 12,
    color: "#5f6f87",
    fontSize: 13,
    lineHeight: 18,
  },
  testButton: {
    borderWidth: 1,
    borderColor: "#15926f",
    backgroundColor: "#eafaf6",
    borderRadius: 12,
    alignItems: "center",
    paddingVertical: 11,
    marginBottom: 10,
  },
  testButtonDisabled: {
    opacity: 0.75,
  },
  testButtonText: {
    color: "#0d7c5e",
    fontWeight: "700",
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: "#2d6cdf",
    borderRadius: 14,
    alignItems: "center",
    paddingVertical: 12,
    marginBottom: 12,
  },
  secondaryButtonText: {
    color: "#2d6cdf",
    fontWeight: "700",
  },
  codeBox: {
    backgroundColor: "#f2f7ff",
    borderColor: "#d5e4fb",
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  codeLabel: {
    fontSize: 12,
    color: "#60718a",
    marginBottom: 3,
    fontWeight: "600",
  },
  codeValue: {
    color: "#1c54b2",
    fontWeight: "800",
    fontSize: 20,
    letterSpacing: 1.4,
  },
  connectHint: {
    marginTop: 6,
    color: "#5f6f87",
    fontSize: 12,
    lineHeight: 17,
  },
  recentTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1f2430",
    marginBottom: 12,
  },
  emptyCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dce6f4",
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  emptyRecentText: {
    color: "#5f6f87",
    fontSize: 14,
    fontWeight: "600",
  },
  emptyRecentSubtext: {
    color: "#8594aa",
    fontSize: 13,
    marginTop: 4,
  },
  recentListContent: {
    paddingBottom: 6,
  },
  recentItem: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dce6f4",
    borderRadius: 16,
    paddingHorizontal: 13,
    paddingVertical: 13,
    marginBottom: 12,
    shadowColor: "#0f2c5c",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  recentTopRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  recentAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2d6cdf",
    marginRight: 10,
  },
  recentAvatarText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 16,
  },
  recentTextWrap: {
    flex: 1,
  },
  recentName: {
    color: "#1f2430",
    fontWeight: "600",
    fontSize: 15,
  },
  recentMeta: {
    color: "#7385a0",
    fontSize: 12,
    marginTop: 3,
  },
  connectionBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 99,
  },
  connectionBadgeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  recentMessage: {
    color: "#60718a",
    marginTop: 10,
    fontSize: 13,
  },
});

export default chatListStyles;
